version: "3.6"
services:
    redis:
        image: "redis:alpine"
        hostname: redis
        ports:
        - "6379:6379"

    work.api:
        build: .
        ports:
            - "8080:80"
        depends_on:
            - redis
        command: sh -c "/wait && /sayhello"
        environment:
            - WAIT_HOSTS=redis:6379
            - WAIT_HOSTS_TIMEOUT=300
            - WAIT_SLEEP_INTERVAL=30
            - WAIT_HOST_CONNECT_TIMEOUT=30
     
    ms-sql-server:
        image: "mcr.microsoft.com/mssql/server:2017-latest-ubuntu"
        environment:
            SA_PASSWORD: "Lemoon321!"
            ACCEPT_EULA: "Y"
            MSSQL_PID: Express

      
        
   